# Generated by Django 2.2.1 on 2019-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('class_no', models.IntegerField(verbose_name='班级')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('born', models.DateField(verbose_name='生日')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='账户余额')),
                ('description', models.TextField(null=True, verbose_name='个性签名')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'db_table': 'tb_student',
            },
        ),
    ]
