# Generated by Django 2.2.1 on 2019-05-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='born',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='账户余额'),
        ),
    ]
