# Generated by Django 2.2.1 on 2019-06-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tb_student',
        ),
    ]
