# Generated by Django 2.2.2 on 2019-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='姓名', max_length=15, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, help_text='性别', verbose_name='性别'),
        ),
    ]
